network:
  name: xception_net
  num_classes: '@{dataset.num_classes}'
  pretrained: False          # set 'True' to load pretrained model
  checkpoint: './networks/xception-b5690688.pth'            # ignore if pretrained is false
  num_gpus: '@{num_gpus}'
weight_energy:
  name: weight_energy
  num_classes: '@{dataset.num_classes}'
  pretrained: False          # set 'True' to load pretrained model
  checkpoint:           # ignore if pretrained is false
  num_gpus: '@{num_gpus}'
logistic_regression:
  name: weight_energy
  num_classes: '@{dataset.num_classes}'
  pretrained: False          # set 'True' to load pretrained model
  checkpoint:             # ignore if pretrained is false
  num_gpus: '@{num_gpus}'
